import Head from 'next/head';

const HTMLHead = () => {
    return (
        <Head>
            <title>GROC</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
};

export default HTMLHead;